config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/palomoIFCA/test-2-notebooks:
      branch: main
      repo: https://gitlab.a.incd.pt/palomoIFCA/test-2-notebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-alizarin-sparrow.sh
        container: qc.acc_jumpy-brass-gopher
  QC.Doc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-scarlet-squid.sh
        container: qc.doc_slimy-platinum-zonkey
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-brass-ray.sh
        container: qc.doc_messy-bistre-akita
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-seashell-mastiff.sh
        container: qc.doc_squirrely-cinnabar-havanese
  QC.Lic:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-russet-lobster.sh
        container: qc.lic_homey-salmon-ferret
  QC.Sec:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-chocolate-chipmunk.sh
        container: qc.sec_sickly-myrtle-toucan
  QC.Sty:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-chartreuse-mandrill.sh
        container: qc.sty_flaky-maroon-yak
  QC.Uni:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-platinum-peccary.sh
        container: qc.uni_cheeky-puce-flamingo
  QC.Ver:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-black-ragdoll.sh
        container: qc.ver_gummy-ultramarine-bloodhound
timeout: 5400
