config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/palomoIFCA/test-2-notebooks:
      branch: main
      repo: https://gitlab.a.incd.pt/palomoIFCA/test-2-notebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-magenta-macaque.sh
        container: qc.acc_squirrely-purple-mayfly
  QC.Doc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-flax-quetzal.sh
        container: qc.doc_breezy-apricot-stingray
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-cerulean-worm.sh
        container: qc.doc_queasy-ecru-bordeaux
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-emerald-penguin.sh
        container: qc.doc_wheezy-malachite-insect
  QC.Lic:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-turquoise-pinscher.sh
        container: qc.lic_randy-razzmatazz-rottweiler
  QC.Sty:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-salmon-squirrel.sh
        container: qc.sty_clammy-pumpkin-toad
  QC.Ver:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-russet-gar.sh
        container: qc.ver_chummy-cobalt-zebu
timeout: 5400
