config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/palomoIFCA/test-2-notebooks:
      branch: main
      repo: https://gitlab.a.incd.pt/palomoIFCA/test-2-notebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-silver-catfish.sh
        container: qc.acc_hazy-flax-dragon
  QC.Doc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-buff-collie.sh
        container: qc.doc_chummy-gold-bracke
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-champagne-schnauzer.sh
        container: qc.doc_crappy-teal-gibbon
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-bronze-bandicoot.sh
        container: qc.doc_skimpy-white-llama
  QC.Lic:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-firebrick-spoonbill.sh
        container: qc.lic_leaky-lilac-donkey
  QC.Sty:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-aqua-gharial.sh
        container: qc.sty_muzzy-champagne-paradise
  QC.Ver:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-aquamarine-hornet.sh
        container: qc.ver_tasty-saffron-booby
timeout: 5400
