config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/palomoIFCA/test-2-notebooks:
      branch: main
      repo: https://gitlab.a.incd.pt/palomoIFCA/test-2-notebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-tangerine-chameleon.sh
        container: qc.acc_cranky-buff-liger
  QC.Doc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-pink-crab.sh
        container: qc.doc_squeaky-olivine-skunk
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-tomato-antelope.sh
        container: qc.doc_sloppy-pear-rat
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-eggplant-hyrax.sh
        container: qc.doc_cranky-zucchini-spitz
  QC.Lic:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-lilac-hamster.sh
        container: qc.lic_squeaky-firebrick-birman
  QC.Sty:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-yellow-buzzard.sh
        container: qc.sty_droopy-sapphire-gopher
  QC.Ver:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-harlequin-sparrow.sh
        container: qc.ver_wheezy-white-scorpion
timeout: 5400
