config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/palomoIFCA/test-2-notebooks:
      branch: main
      repo: https://gitlab.a.incd.pt/palomoIFCA/test-2-notebooks
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-wisteria-wallaby.sh
        container: qc.acc_muzzy-denim-hyrax
  QC.Doc:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-jade-dugong.sh
        container: qc.doc_lovely-taupe-pig
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-aqua-olm.sh
        container: qc.doc_smelly-champagne-labradoodle
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-aquamarine-tang.sh
        container: qc.doc_hilly-cinnabar-akita
  QC.Lic:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-aqua-bandicoot.sh
        container: qc.lic_lanky-plum-newt
  QC.Sec:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-harlequin-mammoth.sh
        container: qc.sec_gummy-gamboge-meerkat
  QC.Sty:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-chartreuse-eagle.sh
        container: qc.sty_tacky-rust-wolverine
  QC.Uni:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-fuchsia-raccoon.sh
        container: qc.uni_homely-periwinkle-giraffe
  QC.Ver:
    repos:
      gitlab.a.incd.pt/palomoIFCA/test-2-notebooks get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-wisteria-bordeaux.sh
        container: qc.ver_lanky-cream-quetzal
timeout: 5400
